Data cleaning using Pandas

The point of this notebook is to clean up the dataset, So that it only contains customers who can be contacted.

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
df= pd.read_excel(r'./Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

Errors observed within the dataset:

1. Null entries in some columns
2. Inconsistent naming convention.
3. unwanted characters found within entries.

In [3]:
# dropping duplicate rows (if there are any)
df = df.drop_duplicates()

---

Checking column wise for what needs resolving

1. Customer ID Column

In [4]:
# Upon a glance it seems fine, and accurate, but as a good practice, I'll inspect the column.
df['CustomerID'].info()
# It has no missing entries, and all 20 entries are integer datatypes with a consistent naming convention.

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: CustomerID
Non-Null Count  Dtype
--------------  -----
20 non-null     int64
dtypes: int64(1)
memory usage: 320.0 bytes

2. First Name

In [5]:
# Upon a glance, this column also seems fine, but still its worth inspecting.
df['First_Name'].info()
df['First_Name'].describe()
# The column has 20 entries, with 19 of it being unique. All 20 entries have a consistent naming convention

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: First_Name
Non-Null Count  Dtype
--------------  -----
20 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

count      20
unique     19
top       Ron
freq        2
Name: First_Name, dtype: object

3. Last Name

In [6]:
df['Last_Name'].info()
# This column has some issues to it, there's a null entry, and the naming conventions don't tally.
# Removing the unwanted special characters observed in the column
df['Last_Name'] = df['Last_Name'].str.strip("/._")

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: Last_Name
Non-Null Count  Dtype
--------------  -----
19 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

4. Phone Number

In [7]:
df['Phone_Number'].info()
# The phone numbers don't have a standard naming convention, and then there is also some null entries.

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: Phone_Number
Non-Null Count  Dtype
--------------  -----
18 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

In [8]:
# clearing out the characters messing up the ideal number convention
df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]','',regex = True)

# converting the elements in phone number column into strings
df['Phone_Number']= df['Phone_Number'].apply(lambda x: str(x))

# Adding "-" between the numbers for the ideal phone number naming convention
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3]+"-"+x[3:6]+"-"+x[6:10])

# Removing the Na-- and nan-- entries
df['Phone_Number'] = df['Phone_Number'].str.replace('nan--','')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na--','')

# Preview
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2
3     123-543-2345
4     876-678-3469
5     304-762-2467
6
7     876-678-3469
8
9     123-545-5421
10
11
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17
18
19    876-678-3469
Name: Phone_Number, dtype: object

5. Address

In [9]:
# SPlitting the address into three columns: Street address, State and Zip Code.
df['Address'].info()
df[["Street_Address","State","Zip_Code"]] = df["Address"].str.split(",",n=2,expand = True)

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: Address
Non-Null Count  Dtype
--------------  -----
20 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

In [10]:
# dropping the address column
df.drop(columns = "Address", axis = 1, inplace=True)

6. Paying Customer

In [11]:
# This column has inconsistent naming conventions.
df['Paying Customer'].info()
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes','Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No','N')

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: Paying Customer
Non-Null Count  Dtype
--------------  -----
20 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

7. Do not Contact

In [12]:
df['Do_Not_Contact'].info()
# Fixing the inconsistent naming conventions
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No','N')

<class 'pandas.core.series.Series'>
Index: 20 entries, 0 to 19
Series name: Do_Not_Contact
Non-Null Count  Dtype
--------------  -----
16 non-null     object
dtypes: object(1)
memory usage: 320.0+ bytes

8. Not Useful Column

In [13]:
# As the name suggests, its not a useful column. So I'll drop it
df = df.drop(columns = 'Not_Useful_Column',axis = 1)

In [14]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number',
       'Paying Customer', 'Do_Not_Contact', 'Street_Address', 'State',
       'Zip_Code'],
      dtype='object')

Again, this dataset would have to ignore the customers who don't want to be contacted.

In [15]:
# Setting the rows with N/a to an empty string
df = df.replace('N/a','')
# Filling the null entries with empty strings.
df = df.fillna('')

In [16]:
# Removing customers who don't want to be contacted from the overall dataset
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace = True)

In [17]:
# Removing customers without phone numbers
for x in df.index:
    if df.loc[x,"Phone_Number"] == "":
        df.drop(x, inplace = True)

In [18]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

And finally, rewriting the index column,

In [19]:
df = df.reset_index(drop = True)

In [20]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [21]:
# And now, zip code column is completely empty. Might as well drop it.

df.drop(columns= "Zip_Code", axis = 1, inplace=True)

---

Saving the now cleaned up dataset as a csv

In [22]:
df.to_csv('./Cleaned_Customer_Call_List.csv', encoding='utf-8', index = False)

In [23]:
df = pd.read_csv('./Cleaned_Customer_Call_List.csv')
df.head()

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Address,State
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire
1,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,NaN
2,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,NaN
3,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York
4,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,NaN